const citiesData = [
		'Adilabad',
		'Anantapur',
		'Chittoor',
		'Kakinada',
		'Guntur',
		'Hyderabad',
		'Karimnagar',
		'Khammam',
		'Krishna',
		'Kurnool',
		'Mahbubnagar',
		'Medak',
		'Nalgonda',
		'Nizamabad',
		'Ongole',
		'Hyderabad',
		'Srikakulam',
		'Nellore',
		'Visakhapatnam',
		'Vizianagaram',
		'Warangal',
		'Eluru',
		'Kadapa',
		'Anjaw',
		'Changlang',
		'East Siang',
		'Kurung Kumey',
		'Lohit',
		'Lower Dibang Valley',
		'Lower Subansiri',
		'Papum Pare',
		'Tawang',
		'Tirap',
		'Dibang Valley',
		'Upper Siang',
		'Upper Subansiri',
		'West Kameng',
		'West Siang',
		'Baksa',
		'Barpeta',
		'Bongaigaon',
		'Cachar',
		'Chirang',
		'Darrang',
		'Dhemaji',
		'Dima Hasao',
		'Dhubri',
		'Dibrugarh',
		'Goalpara',
		'Golaghat',
		'Hailakandi',
		'Jorhat',
		'Kamrup',
		'Kamrup Metropolitan',
		'Karbi Anglong',
		'Karimganj',
		'Kokrajhar',
		'Lakhimpur',
		'Marigaon',
		'Nagaon',
		'Nalbari',
		'Sibsagar',
		'Sonitpur',
		'Tinsukia',
		'Udalguri',
		'Central Delhi',
		'East Delhi',
		'New Delhi',
		'North Delhi',
		'North East Delhi',
		'North West Delhi',
		'South Delhi',
		'South West Delhi',
		'West Delhi',
		'North Goa',
		'South Goa',
		'Ahmedabad',
		'Amreli district',
		'Anand',
		'Banaskantha',
		'Bharuch',
		'Bhavnagar',
		'Dahod',
		'The Dangs',
		'Gandhinagar',
		'Jamnagar',
		'Junagadh',
		'Kutch',
		'Kheda',
		'Mehsana',
		'Narmada',
		'Navsari',
		'Patan',
		'Panchmahal',
		'Porbandar',
		'Rajkot',
		'Sabarkantha',
		'Surendranagar',
		'Surat',
		'Vyara',
		'Vadodara',
		'Valsad',
		'Bagalkot',
		'Bangalore Rural',
		'Bangalore Urban',
		'Belgaum',
		'Bellary',
		'Bidar',
		'Bijapur',
		'Chamarajnagar',
		'Chikkamagaluru',
		'Chikkaballapur',
		'Chitradurga',
		'Davanagere',
		'Dharwad',
		'Dakshina Kannada',
		'Gadag',
		'Gulbarga',
		'Hassan',
		'Haveri district',
		'Kodagu',
		'Kolar',
		'Koppal',
		'Mandya',
		'Mysore',
		'Raichur',
		'Shimoga',
		'Tumkur',
		'Udupi',
		'Uttara Kannada',
		'Ramanagara',
		'Yadgir',
		'Alappuzha',
		'Ernakulam',
		'Idukki',
		'Kannur',
		'Kasaragod',
		'Kollam',
		'Kottayam',
		'Kozhikode',
		'Malappuram',
		'Palakkad',
		'Pathanamthitta',
		'Thrissur',
		'Thiruvananthapuram',
		'Wayanad',
		'Ahmednagar',
		'Akola',
		'Amravati',
		'Aurangabad',
		'Bhandara',
		'Beed',
		'Buldhana',
		'Chandrapur',
		'Dhule',
		'Gadchiroli',
		'Gondia',
		'Hingoli',
		'Jalgaon',
		'Jalna',
		'Kolhapur',
		'Latur',
		'Mumbai City',
		'Mumbai suburban',
		'Nandurbar',
		'Nanded',
		'Nagpur',
		'Nashik',
		'Osmanabad',
		'Parbhani',
		'Pune',
		'Raigad',
		'Ratnagiri',
		'Sindhudurg',
		'Sangli',
		'Solapur',
		'Satara',
		'Thane',
		'Wardha',
		'Washim',
		'Yavatmal',
		'Karaikal',
		'Mahe',
		'Pondicherry',
		'Yanam',
]

export default {citiesData};
